[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "1b6f06ac6d99b79a8784a690a7e45229f07d40ba"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "73171e1d5bdd62773608c748e5dd92650f7b8cf66145ed4dd2709af16070a8eb"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.0.1+0/libpolymake_julia.v0.0.1.x86_64-apple-darwin14.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f7ace8338a9661f5ba3977c9e21fd49199ee7a8"
libc = "glibc"
libstdcxx_version = "3.4.23"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "c3a491f4273abb5ff42539a468df2a36634c9a6c6b93bd85d06a97d16603a021"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.0.1+0/libpolymake_julia.v0.0.1.x86_64-linux-gnu-libstdcxx23-cxx11.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36dbfa9a359fd51de387f4e32843570bb24e3a84"
libc = "glibc"
libstdcxx_version = "3.4.25"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "3d64d1196eded558c6e16f1ecb1cbb6541a2e3571d6fbda48aa6af54b71cc8ab"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.0.1+0/libpolymake_julia.v0.0.1.x86_64-linux-gnu-libstdcxx25-cxx11.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cc2714285836de5101e991a8c93a618ebdca196"
libc = "glibc"
libstdcxx_version = "3.4.26"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "0f3dd9990380cbb1eedae906cd1d17cb1e60bebcf82960dcf3ccd8fe5072d17c"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.0.1+0/libpolymake_julia.v0.0.1.x86_64-linux-gnu-libstdcxx26-cxx11.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f170236e2e29ad85f43baa7e7c8f11d2f4c0845a"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "4c3d5c05ff0784f8526be37880b0c04fc287fc14e7ef6c9396c4f82462e6f6d0"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.0.3+0/libpolymake_julia.v0.0.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "563a3ba362d046e9ea2cac51bc291d9d324c586f"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "296600e2711a48fd008036d6827fa6e43c609bc3cfe3df40df699c02b211e26d"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.0.3+0/libpolymake_julia.v0.0.3.x86_64-linux-gnu-cxx11.tar.gz"
