[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcc29ba2178f40bfe4905fd52ec2ec613fe41788"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "9023fa182a8e4596c90696ab48bd42980efdd96a2a48107e90257bc0af71953e"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.1.0+0/libpolymake_julia.v0.1.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "354d01d4a5bbe86f42d65524442d766d45c04284"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "04db5a17e6810c3f92456428105f62d2e233362abb3af12d99b202fc6b00c2c6"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.1.0+0/libpolymake_julia.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
