[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "5e5b1cb7de4642121a4a64ff63e21769e8d57d19"
julia_version = "1.6.0"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "6da7be02a6ecb6754f2538e620783661f3931f9c8e0a908a754ebd2ffc3ba946"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.400+0/libpolymake_julia.v0.4.400.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "be0c4777faedf09c753276b39349b0a6acddf757"
julia_version = "1.7.0"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "eead0316962a843374325e256f6c2cd33153e5250708fdc095f332b2a05e13ad"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.400+0/libpolymake_julia.v0.4.400.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22a2e1a8815f5b2524e0acf251d6bf3673aba515"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "e2c2e9e3503f36f055ef0e36c82eb601dda6554d702398a08dc48efdbd0515ba"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.400+0/libpolymake_julia.v0.4.400.x86_64-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11a592886dae6158d12316712b028c7f8dd8ea7c"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "409347c732e77a2410e380709d56e7f6f57fad20afaf9aba48f1d09d1709c182"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.400+0/libpolymake_julia.v0.4.400.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f81b7e7da8f0691d261e3a6ec5a0d36f58a75435"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "a19b3cb4760438772c04f0802571ab77e35379ebc2f431b5a67fb937fa2d2336"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.400+0/libpolymake_julia.v0.4.400.x86_64-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0880580e9b33074bf001e9a8ba937354889d34b1"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "598ea280cb8f2dc10831045d2c2ff6d265d09483456a7fd665985da81f0f131c"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.400+0/libpolymake_julia.v0.4.400.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "5c923e695f3867613ada4f50924daf5d6c823d8e"
julia_version = "1.6.0"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "4bfc52c6536d53c87f9a11f49354ef554d0894dd6160bda9fbcc45efd177ad54"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "65b3d6bbd724f7f4c7705d1d6a8a2bc941fb8ccb"
julia_version = "1.7.0"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "864dc150f1a4970d4a7257194a4bf64781bf6279b436205a9714780ef31220c1"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "3ef51d0bd01b6cc81013a71f3be53c97ad44d512"
julia_version = "1.8.0"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "409a35676ce5b4354d7d94a425b9d4daa6f2bfcf9dc6dadf62840c179b8c7d9e"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac86e2cc3d51f54cbb856d38a3cd0ba57961b299"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "ac3610699b1ee75457d3c79e0aee7a05c9b08d61761dbd59262f26c051f4e21b"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90961590479b4c4c85e056a7714b5ab5eb3d299e"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "3997900df98671c09a6d533f40bc523b282b2fe50006c7389e1f1b2a262a8b0c"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2efdc6aa2a298571134266434105955ccbc5f6ed"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "aebe1bc6dda0646b8c624ad52db740ee4ff19877060b1d17c61b72d024481e15"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d2ca61dd1857c9a7b4eec2f67bb4113f805d4f5"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "4bb916e2755ba2ac6af43a7cae426f70a78d15a93bdf53275b4b7f3bbfa670c5"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d75f794c6c6ee349b43c50830ac71e97d8f4669b"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "c2b00b49c487ca4ec690583089f14577e45b00322273ce8a92610c15affc187a"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97791d1d763f45b654ad9380440897e42cac37d0"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "48f6eee4f28b3a0678681a63cda7a79a003f9deb49974e3e317a940c0fc29fb7"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "4397285224126bb2a794caaf56160b47a2f2707c"
julia_version = "1.6.0"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "fde64a16686562f9505503f966c67f51fcac9fdcbf6e235503b90f51cbf92b70"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "a28980bbacb79c555d85b384c9fa34c20891cf6f"
julia_version = "1.7.0"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "528fd2a6592d48a07d1e527c1e325abe01b34b8a465928d260ac34026c8f7e0e"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "8b27c59177f46ca0bb4f05d3bd47de48e6f65705"
julia_version = "1.8.0"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "4bb28098a2ac66647b312f8fc6059500cb37553bb5824629d4baa386a5b66c32"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e4e061818c4204e30f46d30381e52db05e8afd8"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "3033d4aa0d889419bdef0b69abc4648acaf060233d2557737b53726e2070576d"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ae1b9db83b5a75fd867231ad84cfc181d36eb0f"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "246b83c3fcccf64d527afca7dfb8a64cb4e1a6f2a50f574db5b21776d9cbaaa8"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3282d57ea810f3d439f10e2d50a500f9ff2d5c5b"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "833104d65c15e638bcd03efaec022cd5ca6b63a6b4d7f534505b25ca1ce74efd"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34ff2e4e355d26cc3197de469c8ef4e4702b7928"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "b0d47aeeeda3e0b3d93ca314ed3873197fd7f24e15f45c0ec5a2a115be162b56"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7b64c0b8bce4c7928c3d3b622205ae23e0c26a3"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "c976ec6907d8843c8b3476a953190b77416d583d78aace567b9dc3f0af763492"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68d59d0ea0fe0bf7101d3febbd485937db584d0a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "c601c8ff0f0911b17bbf3d342ab2956e9901b80b741d043db4389cc9acfcea87"
    url = "https://github.com/benlorenz/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.5.0+0/libpolymake_julia.v0.5.0.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
